"""
Build a liquid swing watchlist from local CSVs (avg dollar volume + min price).

Default output: config/watchlists/swing_liquid.txt (~500 names).
Always includes SPY for regime filters.
"""
import argparse
import os
import sys

import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.data.csv_utils import read_swing_csv

DATA_DIR = "data/historical_swing"
DEFAULT_OUT = "config/watchlists/swing_liquid.txt"
DEFAULT_SOURCE = "config/watchlists/my_portfolio.txt"


def _load_symbol_universe(source_file: str | None) -> list[str]:
    if source_file and os.path.exists(source_file):
        with open(source_file, encoding="utf-8") as f:
            return [ln.strip().upper() for ln in f if ln.strip() and not ln.startswith("#")]
    return []


def score_symbols(
    data_dir: str,
    universe: list[str],
    lookback_days: int = 60,
    min_price: float = 5.0,
    min_avg_dollar_vol: float = 5_000_000.0,
) -> pd.DataFrame:
    rows = []
    if universe:
        candidates = universe
    else:
        candidates = [
            f.replace("_1D.csv", "").upper()
            for f in os.listdir(data_dir)
            if f.endswith("_1D.csv")
        ]

    for sym in candidates:
        path = os.path.join(data_dir, f"{sym}_1D.csv")
        if not os.path.exists(path):
            continue
        df = read_swing_csv(path)
        if df.empty or len(df) < 20:
            continue
        tail = df.tail(lookback_days)
        if "Close" not in tail.columns or "Volume" not in tail.columns:
            continue
        avg_close = float(tail["Close"].mean())
        avg_vol = float(tail["Volume"].mean())
        dollar_vol = avg_close * avg_vol
        if avg_close < min_price or dollar_vol < min_avg_dollar_vol:
            continue
        rows.append({
            "symbol": sym,
            "avg_close": avg_close,
            "avg_dollar_vol": dollar_vol,
        })

    if not rows:
        return pd.DataFrame()
    out = pd.DataFrame(rows).sort_values("avg_dollar_vol", ascending=False)
    return out


def main():
    ap = argparse.ArgumentParser(description="Build liquid swing watchlist from CSVs")
    ap.add_argument("--source", default=DEFAULT_SOURCE,
                    help="Optional symbol list to filter (default: my_portfolio.txt)")
    ap.add_argument("--output", default=DEFAULT_OUT)
    ap.add_argument("--top", type=int, default=500)
    ap.add_argument("--min-price", type=float, default=5.0)
    ap.add_argument("--min-dollar-vol", type=float, default=5_000_000.0)
    ap.add_argument("--lookback-days", type=int, default=60)
    args = ap.parse_args()

    universe = _load_symbol_universe(args.source if os.path.exists(args.source) else None)
    ranked = score_symbols(
        DATA_DIR,
        universe,
        lookback_days=args.lookback_days,
        min_price=args.min_price,
        min_avg_dollar_vol=args.min_dollar_vol,
    )
    if ranked.empty:
        print("No symbols passed liquidity filters.")
        return

    picks = ranked.head(args.top)["symbol"].tolist()
    if "SPY" not in picks:
        picks = ["SPY"] + [s for s in picks if s != "SPY"]

    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as f:
        f.write("# Liquid swing universe (avg $ volume rank, generated by build_liquid_watchlist.py)\n")
        for sym in picks:
            f.write(f"{sym}\n")

    print(f"Wrote {len(picks)} symbols -> {args.output}")
    print(f"  Median avg $ vol: ${ranked.head(args.top)['avg_dollar_vol'].median():,.0f}")


if __name__ == "__main__":
    main()
